// Copyright 2026 Coach Workout Tools Contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"btwb-pp-cli/internal/cli"
	"btwb-pp-cli/internal/cliutil"
	"btwb-pp-cli/internal/client"
	"btwb-pp-cli/internal/config"
	"btwb-pp-cli/internal/mcp/cobratree"
	"btwb-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("members_tracks_list",
			mcplib.WithDescription("Track ids and names. The ids are what `--track-ids` on the widget commands takes, and what `--track` filters the whiteboard by. Required: memberId. Returns the TracksListResponse."),
			mcplib.WithString("memberId", mcplib.Required(), mcplib.Description("btwb member id. Defaults to the logged-in member.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/members/{memberId}/tracks", []mcpParamBinding{{PublicName: "memberId", WireName: "memberId", Location: "path"}, }, []string{"memberId", }),
	)
	s.AddTool(
		mcplib.NewTool("members_whiteboard_get-day",
			mcplib.WithDescription("Every workout scheduled for the given date across the tracks the member follows, plus any result the member already logged that day. This is the 'what is the workout today' call. Required: memberId, d. Returns the WhiteboardDay."),
			mcplib.WithString("memberId", mcplib.Required(), mcplib.Description("btwb member id. Defaults to the logged-in member.")),
			mcplib.WithString("d", mcplib.Required(), mcplib.Description("Date to read, as YYYY-MM-DD.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/members/{memberId}/whiteboard/day", []mcpParamBinding{{PublicName: "memberId", WireName: "memberId", Location: "path"},{PublicName: "d", WireName: "d", Location: "query"}, }, []string{"memberId", }),
	)
	s.AddTool(
		mcplib.NewTool("members_whiteboard_get-month",
			mcplib.WithDescription("Same shape as the day view, for every day of the month containing the given date. Use it to pull a training block in one call. Required: memberId, d. Returns the WhiteboardGetMonthResponse."),
			mcplib.WithString("memberId", mcplib.Required(), mcplib.Description("btwb member id. Defaults to the logged-in member.")),
			mcplib.WithString("d", mcplib.Required(), mcplib.Description("Any date inside the month to read, as YYYY-MM-DD.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/members/{memberId}/whiteboard/month", []mcpParamBinding{{PublicName: "memberId", WireName: "memberId", Location: "path"},{PublicName: "d", WireName: "d", Location: "query"}, }, []string{"memberId", }),
	)
	s.AddTool(
		mcplib.NewTool("members_workout-sessions_list-sessions",
			mcplib.WithDescription("List the member's logged results, most recent first. Required: memberId. Optional: page (default: 1). Returns the WorkoutSessionsListSessionsResponse."),
			mcplib.WithString("memberId", mcplib.Required(), mcplib.Description("btwb member id. Defaults to the logged-in member.")),
			mcplib.WithString("page", mcplib.Description("Page of results, 1-based.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/members/{memberId}/workout_sessions", []mcpParamBinding{{PublicName: "memberId", WireName: "memberId", Location: "path"},{PublicName: "page", WireName: "page", Location: "query"}, }, []string{"memberId", }),
	)
	s.AddTool(
		mcplib.NewTool("tasks_get-event",
			mcplib.WithDescription("The complete workout: its description as written by the coach, the scoring variant, how many members already logged a result, and the member's own previous result for the same workout. Required: memberId, trackEventId. Returns the Wod."),
			mcplib.WithString("memberId", mcplib.Required(), mcplib.Description("btwb member id. Defaults to the logged-in member.")),
			mcplib.WithString("trackEventId", mcplib.Required(), mcplib.Description("Track event id, as found in `detail_path` of a day entry.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/tasks/members/{memberId}/track_events/{trackEventId}", []mcpParamBinding{{PublicName: "memberId", WireName: "memberId", Location: "path"},{PublicName: "trackEventId", WireName: "trackEventId", Location: "path"}, }, []string{"memberId","trackEventId", }),
	)
	s.AddTool(
		mcplib.NewTool("webwidgets_widget-activities",
			mcplib.WithDescription("Get the gym's recent activity feed via the gym's widget key. Required: track_ids. Optional: activity_length (default: 10). Returns the WebwidgetsWidgetActivitiesResponse."),
			mcplib.WithString("track_ids", mcplib.Required(), mcplib.Description("Track ids, comma separated. See `btwb-pp-cli track list`.")),
			mcplib.WithString("activity_length", mcplib.Description("How many results to return.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://webwidgets.prod.btwb.com/webwidgets/activities", []mcpParamBinding{{PublicName: "track_ids", WireName: "track_ids", Location: "query"},{PublicName: "activity_length", WireName: "activity_length", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("webwidgets_widget-leaderboard",
			mcplib.WithDescription("Get a workout's leaderboard via the gym's widget key. Required: track_ids. Optional: leaderboard_length (default: 10). Returns the WebwidgetsWidgetLeaderboardResponse."),
			mcplib.WithString("track_ids", mcplib.Required(), mcplib.Description("Track ids, comma separated. See `btwb-pp-cli track list`.")),
			mcplib.WithString("leaderboard_length", mcplib.Description("Entries to return per sex.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://webwidgets.prod.btwb.com/webwidgets/leaderboards", []mcpParamBinding{{PublicName: "track_ids", WireName: "track_ids", Location: "query"},{PublicName: "leaderboard_length", WireName: "leaderboard_length", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("webwidgets_widget-wods",
			mcplib.WithDescription("The gym-facing JSON API. Returns a wodset per track per day, each with the workout description and optionally the leaderboard and recent results. Requires the gym's Web Widgets key, not a member session. Required: track_ids. Optional: days (default: 0), date, sections (plus 2 more)."),
			mcplib.WithString("track_ids", mcplib.Required(), mcplib.Description("Track ids, comma separated. See `btwb-pp-cli track list`.")),
			mcplib.WithString("days", mcplib.Description("How many days back from `date` to return.")),
			mcplib.WithString("date", mcplib.Description("Last day to return, as YYYY-MM-DD. The upstream expects a JavaScript `Date.toString()` value; this client converts.")),
			mcplib.WithString("sections", mcplib.Description("Restrict to named WOD sections, comma separated.")),
			mcplib.WithString("leaderboard_length", mcplib.Description("Leaderboard entries per workout, per sex. 0 omits them.")),
			mcplib.WithString("activity_length", mcplib.Description("Recent results per workout. 0 omits them.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://webwidgets.prod.btwb.com/webwidgets/wods", []mcpParamBinding{{PublicName: "track_ids", WireName: "track_ids", Location: "query"},{PublicName: "days", WireName: "days", Location: "query"},{PublicName: "date", WireName: "date", Location: "query"},{PublicName: "sections", WireName: "sections", Location: "query"},{PublicName: "leaderboard_length", WireName: "leaderboard_length", Location: "query"},{PublicName: "activity_length", WireName: "activity_length", Location: "query"}, }, []string{ }),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export BTWB_SESSION_COOKIE=<your-key>" +
					"\n      Run 'btwb-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set it with: export BTWB_SESSION_COOKIE=<your-key>" +
					"\n      Run 'btwb-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export BTWB_SESSION_COOKIE=<your-key>" +
					"\n      Run 'btwb-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "btwb-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "btwb-pp-cli", "data.db")
}
// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "btwb",
		"description": "Beyond the Whiteboard (btwb.com) - CrossFit workout tracking. Two channels: 1. **Whiteboard (member session)** - the...",
		"archetype":   "project-management",
		"tool_count":  8,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion btwb-pp-cli binary.",
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
			},
		},
		"resources": []map[string]any{
			{
				"name": "members",
				"description": "Manage members",
				"endpoints": []string{ },
			},
			{
				"name": "tasks",
				"description": "Manage tasks",
				"endpoints": []string{"get-event",  },
			},
			{
				"name": "webwidgets",
				"description": "Manage webwidgets",
				"endpoints": []string{"widget-activities", "widget-leaderboard", "widget-wods",  },
				"searchable": true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		"playbook": []map[string]string{
			{"topic": "Finding stale work", "insight": "Use the stale command or sql query to find items not updated recently. More reliable than scanning list results manually."},
			{"topic": "Load analysis", "insight": "When analyzing team workload, filter by assignee and status. Raw counts without status filtering are misleading."},
			{"topic": "Bulk operations", "insight": "For bulk status changes, prefer update endpoints over delete+create. Most PM APIs track history on updates."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
