// Copyright 2026 Coach Workout Tools Contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCoachGetCalendarCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId int
	var bodyDateFrom string
	var bodyDateTo string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "get-calendar",
		Short: "Содержимое календаря клиента: тренировки, дни отдыха и...",
		Example: "  trenda-pp-cli coach get-calendar --date-from 2026-01-15",
		Annotations: map[string]string{"pp:endpoint": "coach.get-calendar", "pp:method": "POST", "pp:path": "/api/v1/coach/workout/get-by-date"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("client-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "client-id")
				}
				if !cmd.Flags().Changed("date-from") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "date-from")
				}
				if !cmd.Flags().Changed("date-to") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "date-to")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/coach/workout/get-by-date"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyClientId != 0 {
					body["client_id"] = bodyClientId
				}
				if bodyDateFrom != "" {
					body["date_from"] = bodyDateFrom
				}
				if bodyDateTo != "" {
					body["date_to"] = bodyDateTo
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "coach",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&bodyClientId, "client-id", 0, "Идентификатор клиента")
	cmd.Flags().StringVar(&bodyDateFrom, "date-from", "", "Начало интервала, YYYY-MM-DD")
	cmd.Flags().StringVar(&bodyDateTo, "date-to", "", "Конец интервала, YYYY-MM-DD")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
