// Copyright 2026 Coach Workout Tools Contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoachCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "coach",
		Short: "Профиль текущего коуча",
	}

	cmd.AddCommand(newCoachCopyWorkoutCmd(flags))
	cmd.AddCommand(newCoachCreateWorkoutCmd(flags))
	cmd.AddCommand(newCoachDeleteWorkoutCmd(flags))
	cmd.AddCommand(newCoachGetCalendarCmd(flags))
	cmd.AddCommand(newCoachGetCurrentCmd(flags))
	cmd.AddCommand(newCoachGetExerciseHistoryCmd(flags))
	cmd.AddCommand(newCoachGetExercisesByIdsCmd(flags))
	cmd.AddCommand(newCoachGetLastResultCmd(flags))
	cmd.AddCommand(newCoachGetProgramCmd(flags))
	cmd.AddCommand(newCoachListExercisesCmd(flags))
	cmd.AddCommand(newCoachListMetricGroupsCmd(flags))
	cmd.AddCommand(newCoachListProgramWorkoutsCmd(flags))
	cmd.AddCommand(newCoachListProgramsCmd(flags))
	cmd.AddCommand(newCoachUpdateWorkoutCmd(flags))
	cmd.AddCommand(newCoachUpdateWorkoutBodyCmd(flags))
	return cmd
}
