// Copyright 2026 Coach Workout Tools Contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"


type ApiError struct {
	Code string `json:"code"`
	Details json.RawMessage `json:"details"`
	Message string `json:"message"`
}

type CalendarResponse struct {
	Workouts json.RawMessage `json:"workouts"`
}

type Client struct {
	Email string `json:"email"`
	FirstName string `json:"first_name"`
	Id int `json:"id"`
	LastName string `json:"last_name"`
	Status string `json:"status"`
}

type ClientListResponse struct {
	Models json.RawMessage `json:"models"`
	TotalCount int `json:"total_count"`
}

type Coach struct {
	Email string `json:"email"`
	FirstName string `json:"first_name"`
	Id int `json:"id"`
	LastName string `json:"last_name"`
}

type CoachCopyWorkoutResponse struct {
}

type CoachDeleteWorkoutResponse struct {
}

type CoachGetExerciseHistoryResponse struct {
}

type CoachGetLastResultResponse struct {
}

type CoachGetProgramResponse struct {
}

type CoachListMetricGroupsResponse struct {
}

type CoachListProgramWorkoutsResponse struct {
}

type CopyWorkoutRequest struct {
	ClientId int `json:"client_id"`
	Models json.RawMessage `json:"models"`
}

type CreateWorkoutRequest struct {
	ClientId int `json:"client_id"`
	Cooldown json.RawMessage `json:"cooldown"`
	Date string `json:"date"`
	Description string `json:"description"`
	SortOrder int `json:"sort_order"`
	Title string `json:"title"`
	Type string `json:"type"`
	Warmup json.RawMessage `json:"warmup"`
	Workout json.RawMessage `json:"workout"`
}

type DeleteWorkoutRequest struct {
	ClientId int `json:"client_id"`
	Ids json.RawMessage `json:"ids"`
}

type ExerciseListResponse struct {
	HasMore bool `json:"has_more"`
	Models json.RawMessage `json:"models"`
}

type ExerciseModelsResponse struct {
	Models json.RawMessage `json:"models"`
}

type ExerciseSet struct {
	ActualPrimaryUnit float64 `json:"actual_primary_unit"`
	ActualSecondaryUnit float64 `json:"actual_secondary_unit"`
	ActualTertiaryUnit float64 `json:"actual_tertiary_unit"`
	Order int `json:"order"`
	PrimaryUnit string `json:"primary_unit"`
	SecondaryUnit string `json:"secondary_unit"`
	Status string `json:"status"`
	TargetPrimaryUnit float64 `json:"target_primary_unit"`
	TargetSecondaryUnit float64 `json:"target_secondary_unit"`
	TargetTertiaryUnit float64 `json:"target_tertiary_unit"`
	TertiaryUnit string `json:"tertiary_unit"`
}

type ListClientsRequest struct {
	Limit int `json:"limit"`
	Offset int `json:"offset"`
}

type UpdateWorkoutBodyRequest struct {
	Cooldown json.RawMessage `json:"cooldown"`
	Description string `json:"description"`
	Id int `json:"id"`
	Title string `json:"title"`
	Warmup json.RawMessage `json:"warmup"`
	Workout json.RawMessage `json:"workout"`
}

type UpdateWorkoutRequest struct {
	Models json.RawMessage `json:"models"`
}

type VideoV2 struct {
}

type Workout struct {
	Body json.RawMessage `json:"body"`
	ChatId int `json:"chat_id"`
	ClientId int `json:"client_id"`
	CoachId int `json:"coach_id"`
	CommentsCount int `json:"comments_count"`
	Date string `json:"date"`
	Description string `json:"description"`
	HasPendingSync bool `json:"has_pending_sync"`
	Id int `json:"id"`
	ProgramAssignmentId int `json:"program_assignment_id"`
	ProgramWorkoutId int `json:"program_workout_id"`
	SortOrder int `json:"sort_order"`
	Status string `json:"status"`
	Title string `json:"title"`
	Type string `json:"type"`
	WorkoutVersion int `json:"workout_version"`
}

type WorkoutBlock struct {
	Exercises json.RawMessage `json:"exercises"`
	Id string `json:"id"`
	IsSuperset bool `json:"is_superset"`
	SortOrder int `json:"sort_order"`
}

type WorkoutBody struct {
	Cooldown json.RawMessage `json:"cooldown"`
	Warmup json.RawMessage `json:"warmup"`
	Workout json.RawMessage `json:"workout"`
}

type WorkoutExercise struct {
	BothSides bool `json:"both_sides"`
	CanEdit bool `json:"can_edit"`
	Comment string `json:"comment"`
	ComplexDetails string `json:"complex_details"`
	Description string `json:"description"`
	ExerciseId int `json:"exercise_id"`
	Id string `json:"id"`
	MediaFileIds json.RawMessage `json:"media_file_ids"`
	Metric json.RawMessage `json:"metric"`
	PrimaryUnit string `json:"primary_unit"`
	Result string `json:"result"`
	SecondaryUnit string `json:"secondary_unit"`
	Sets json.RawMessage `json:"sets"`
	SortOrder int `json:"sort_order"`
	Status string `json:"status"`
	Tempo string `json:"tempo"`
	Title string `json:"title"`
	Type string `json:"type"`
	VideoUrls json.RawMessage `json:"video_urls"`
	VideosV2 json.RawMessage `json:"videos_v2"`
}
