// Copyright 2026 Coach Workout Tools Contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"


type ContentEnvelope struct {
	Count int `json:"count"`
	Tiles json.RawMessage `json:"tiles"`
}

type ContentTile struct {
	Acf json.RawMessage `json:"acf"`
	ContentType string `json:"content_type"`
	FullPath string `json:"full_path"`
	Id string `json:"id"`
	PublishingState string `json:"publishing_state"`
	Title string `json:"title"`
}

type UsersGetAuthMeResponse struct {
}
