// Copyright 2026 Coach Workout Tools Contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"trenda-pp-cli/internal/cli"
	"trenda-pp-cli/internal/cliutil"
	"trenda-pp-cli/internal/client"
	"trenda-pp-cli/internal/config"
	"trenda-pp-cli/internal/mcp/cobratree"
	"trenda-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("client_get",
			mcplib.WithDescription("Карточка клиента. Required: client_id. Returns the new Client."),
			mcplib.WithString("client_id", mcplib.Required(), mcplib.Description("Идентификатор клиента. Поле называется именно client_id: с полем id...")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/client/get", []mcpParamBinding{{PublicName: "client_id", WireName: "client_id", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("client_list",
			mcplib.WithDescription("Клиенты текущего коуча. Идентификатор клиента из этого списка нужен для работы с календарём. Optional: limit, offset. Returns the new ClientListResponse."),
			mcplib.WithString("limit", mcplib.Description("Limit")),
			mcplib.WithString("offset", mcplib.Description("Offset")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/client/list", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "body"},{PublicName: "offset", WireName: "offset", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_copy-workout",
			mcplib.WithDescription("Копирует тренировку на другую дату или другому клиенту. Дешевле, чем собирать заново. Required: client_id, models. Returns the new CoachCopyWorkoutResponse."),
			mcplib.WithString("client_id", mcplib.Required(), mcplib.Description("Клиент, которому вставляются тренировки")),
			mcplib.WithString("models", mcplib.Required(), mcplib.Description("Тренировки целиком, дата в формате YYYY-MM-DDT00:00:00")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/workout/copy", []mcpParamBinding{{PublicName: "client_id", WireName: "client_id", Location: "body"},{PublicName: "models", WireName: "models", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_create-workout",
			mcplib.WithDescription("Добавляет день в календарь клиента. Содержимое передаётся тремя массивами блоков: warmup (разминка), workout (основная часть), cooldown (заминка). У новых блоков и упражнений идентификатор не указывается, сервер выдаёт его сам. Required: client_id, date, type. Optional: cooldown, description, sort_order (plus 3 more). Returns the new Workout."),
			mcplib.WithString("client_id", mcplib.Required(), mcplib.Description("Идентификатор клиента")),
			mcplib.WithString("cooldown", mcplib.Description("Блоки заминки")),
			mcplib.WithString("date", mcplib.Required(), mcplib.Description("Дата тренировки, YYYY-MM-DD")),
			mcplib.WithString("description", mcplib.Description("Описание или комментарий к тренировке")),
			mcplib.WithString("sort_order", mcplib.Description("Порядок среди тренировок одного дня, обычно 0")),
			mcplib.WithString("title", mcplib.Description("Название тренировки")),
			mcplib.WithString("type", mcplib.Required(), mcplib.Description("Тип дня в календаре")),
			mcplib.WithString("warmup", mcplib.Description("Блоки разминки")),
			mcplib.WithString("workout", mcplib.Description("Блоки основной части")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/workout/add", []mcpParamBinding{{PublicName: "client_id", WireName: "client_id", Location: "body"},{PublicName: "cooldown", WireName: "cooldown", Location: "body"},{PublicName: "date", WireName: "date", Location: "body"},{PublicName: "description", WireName: "description", Location: "body"},{PublicName: "sort_order", WireName: "sort_order", Location: "body"},{PublicName: "title", WireName: "title", Location: "body"},{PublicName: "type", WireName: "type", Location: "body"},{PublicName: "warmup", WireName: "warmup", Location: "body"},{PublicName: "workout", WireName: "workout", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_delete-workout",
			mcplib.WithDescription("Удалить тренировку. Required: client_id, ids. Returns the new CoachDeleteWorkoutResponse."),
			mcplib.WithString("client_id", mcplib.Required(), mcplib.Description("Клиент, которому принадлежат тренировки. Без этого поля сервер...")),
			mcplib.WithString("ids", mcplib.Required(), mcplib.Description("Идентификаторы удаляемых тренировок")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/workout/delete", []mcpParamBinding{{PublicName: "client_id", WireName: "client_id", Location: "body"},{PublicName: "ids", WireName: "ids", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_get-calendar",
			mcplib.WithDescription("Содержимое календаря клиента: тренировки, дни отдыха и восстановления с их идентификаторами. Вызывать перед созданием тренировки, чтобы не задублировать день. Required: client_id, date_from, date_to. Returns the new CalendarResponse."),
			mcplib.WithString("client_id", mcplib.Required(), mcplib.Description("Идентификатор клиента")),
			mcplib.WithString("date_from", mcplib.Required(), mcplib.Description("Начало интервала, YYYY-MM-DD")),
			mcplib.WithString("date_to", mcplib.Required(), mcplib.Description("Конец интервала, YYYY-MM-DD")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/workout/get-by-date", []mcpParamBinding{{PublicName: "client_id", WireName: "client_id", Location: "body"},{PublicName: "date_from", WireName: "date_from", Location: "body"},{PublicName: "date_to", WireName: "date_to", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_get-current",
			mcplib.WithDescription("Возвращает профиль коуча, которому принадлежит сессия. Дешёвая проверка, что сессия жива. Returns the new Coach."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/get-current", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_get-exercise-history",
			mcplib.WithDescription("С какими весами, повторениями и временем клиент выполнял упражнения ранее, от свежих записей к старым. Нужна, чтобы назначать адекватную нагрузку. Клиент здесь задаётся полем user_id: поле client_id молча игнорируется. Без exercise_id возвращается история по всем упражнениям клиента, а она может быть большой: у активного клиента это сотни записей за один ответ. Required: user_id. Optional: exercise_id. Returns the new CoachGetExerciseHistoryResponse."),
			mcplib.WithString("exercise_id", mcplib.Description("Ограничить историю одним упражнением")),
			mcplib.WithString("user_id", mcplib.Required(), mcplib.Description("Идентификатор клиента, именно user_id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/exercise-metric-result/get-history", []mcpParamBinding{{PublicName: "exercise_id", WireName: "exercise_id", Location: "body"},{PublicName: "user_id", WireName: "user_id", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_get-exercises-by-ids",
			mcplib.WithDescription("Возвращает упражнения из библиотеки по списку идентификаторов. Неизвестные идентификаторы молча отбрасываются. Осторожно: с пустым телом эндпоинт отдаёт всю библиотеку целиком, это больше тысячи записей. Optional: ids. Returns the new ExerciseModelsResponse."),
			mcplib.WithString("ids", mcplib.Description("Идентификаторы упражнений")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/exercise/get-by-ids", []mcpParamBinding{{PublicName: "ids", WireName: "ids", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_get-last-result",
			mcplib.WithDescription("Клиент задаётся полем user_id. Валидации нет: при отсутствии данных приходит 200 и result равный null, а не ошибка. Required: user_id. Optional: exercise_id. Returns the new CoachGetLastResultResponse."),
			mcplib.WithString("exercise_id", mcplib.Description("Упражнение, по которому нужен последний результат")),
			mcplib.WithString("user_id", mcplib.Required(), mcplib.Description("Идентификатор клиента, именно user_id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/exercise-metric-result/get-last-result", []mcpParamBinding{{PublicName: "exercise_id", WireName: "exercise_id", Location: "body"},{PublicName: "user_id", WireName: "user_id", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_get-program",
			mcplib.WithDescription("Несмотря на название маршрута, это фильтр-список: принимает массив ids и всегда возвращает массив. Скалярное поле id не распознаётся, и запрос без фильтра отдаёт все программы коуча. Required: ids. Returns the new CoachGetProgramResponse."),
			mcplib.WithString("ids", mcplib.Required(), mcplib.Description("Идентификаторы программ")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/program/get-by-id", []mcpParamBinding{{PublicName: "ids", WireName: "ids", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_list-exercises",
			mcplib.WithDescription("Упражнения, доступные коучу, с их идентификаторами. Идентификатор упражнения обязателен при сборке тренировки. Optional: limit, offset, sort_order. Returns the new ExerciseListResponse."),
			mcplib.WithString("limit", mcplib.Description("Сколько упражнений вернуть, по умолчанию 50")),
			mcplib.WithString("offset", mcplib.Description("Смещение от начала списка")),
			mcplib.WithString("sort_order", mcplib.Description("Порядок сортировки, подтверждено значение IdDesc")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/exercise/get-list", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "body"},{PublicName: "offset", WireName: "offset", Location: "body"},{PublicName: "sort_order", WireName: "sort_order", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_list-metric-groups",
			mcplib.WithDescription("Наборы измеряемых показателей, из которых собираются подходы упражнения. Returns the new CoachListMetricGroupsResponse."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/metric-group/get-list", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_list-program-workouts",
			mcplib.WithDescription("Шаблонные тренировки внутри программы, пригодные для копирования в календарь. Required: program_id. Returns the new CoachListProgramWorkoutsResponse."),
			mcplib.WithString("program_id", mcplib.Required(), mcplib.Description("Идентификатор программы")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/program-workout/get-by-program-id", []mcpParamBinding{{PublicName: "program_id", WireName: "program_id", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_list-programs",
			mcplib.WithDescription("Программы, доступные коучу, включая чужие публичные. Поддерживает пагинацию через limit и offset. Optional: limit, offset. Returns the new ExerciseListResponse."),
			mcplib.WithString("limit", mcplib.Description("Limit")),
			mcplib.WithString("offset", mcplib.Description("Offset")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/program/get-list", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "body"},{PublicName: "offset", WireName: "offset", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_update-workout",
			mcplib.WithDescription("Правит свойства дня: дату, тип, название, описание, порядок среди тренировок одного дня. Содержимое тренировки этим вызовом не меняется. Required: models. Returns the new Workout."),
			mcplib.WithString("models", mcplib.Required(), mcplib.Description("Тренировки с изменёнными полями")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/workout/update", []mcpParamBinding{{PublicName: "models", WireName: "models", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("coach_update-workout-body",
			mcplib.WithDescription("Перезаписывает разминку, основную часть и заминку существующей тренировки. Required: id. Optional: cooldown, description, title (plus 2 more). Returns the new Workout."),
			mcplib.WithString("cooldown", mcplib.Description("Cooldown")),
			mcplib.WithString("description", mcplib.Description("Description")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Идентификатор тренировки")),
			mcplib.WithString("title", mcplib.Description("Title")),
			mcplib.WithString("warmup", mcplib.Description("Warmup")),
			mcplib.WithString("workout", mcplib.Description("Workout")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/coach/workout/update-body", []mcpParamBinding{{PublicName: "cooldown", WireName: "cooldown", Location: "body"},{PublicName: "description", WireName: "description", Location: "body"},{PublicName: "id", WireName: "id", Location: "body"},{PublicName: "title", WireName: "title", Location: "body"},{PublicName: "warmup", WireName: "warmup", Location: "body"},{PublicName: "workout", WireName: "workout", Location: "body"}, }, []string{ }),
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Sign in again: trenda-pp-cli auth login" +
					"\n      See API docs: https://app.trenda.coach" +
					"\n      Run 'trenda-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Sign in again: trenda-pp-cli auth login" +
					"\n      See API docs: https://app.trenda.coach" +
					"\n      Run 'trenda-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Sign in again: trenda-pp-cli auth login" +
					"\n      See API docs: https://app.trenda.coach" +
					"\n      Run 'trenda-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "trenda-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 2)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "trenda-pp-cli", "data.db")
}
// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "trenda",
		"description": "Внутренний API веб-приложения Trenda Coach (app.trenda.coach) - платформы для...",
		"archetype":   "generic",
		"tool_count":  17,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion trenda-pp-cli binary.",
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
				{
					"name": "TRENDA_SESSION",
					"kind": "per_call",
					"required": true,
					"sensitive": true,
					"description": "Set to your API credential.",
				},
			},
			"docs_url": "https://app.trenda.coach",
		},
		"resources": []map[string]any{
			{
				"name": "client",
				"description": "Клиенты коуча и заметки по ним",
				"endpoints": []string{"get", "list",  },
			},
			{
				"name": "coach",
				"description": "Профиль текущего коуча",
				"endpoints": []string{"copy-workout", "create-workout", "delete-workout", "get-calendar", "get-current", "get-exercise-history", "get-exercises-by-ids", "get-last-result", "get-program", "list-exercises", "list-metric-groups", "list-program-workouts", "list-programs", "update-workout", "update-workout-body",  },
				"searchable": true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
