// Copyright 2026 Coach Workout Tools Contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMembersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "members",
		Short: "Manage members",
		Hidden: true,
	}

	cmd.AddCommand(newMembersTracksCmd(flags))
	cmd.AddCommand(newMembersWhiteboardCmd(flags))
	cmd.AddCommand(newMembersWorkoutSessionsCmd(flags))
	return cmd
}
