// Copyright 2026 Coach Workout Tools Contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMembersWorkoutSessionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "workout-sessions",
		Short: "Manage workout sessions",
	}

	cmd.AddCommand(newMembersWorkoutSessionsListSessionsCmd(flags))
	return cmd
}
