// Copyright 2026 Coach Workout Tools Contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMembersWhiteboardCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "whiteboard",
		Short: "Manage whiteboard",
	}

	cmd.AddCommand(newMembersWhiteboardGetDayCmd(flags))
	cmd.AddCommand(newMembersWhiteboardGetMonthCmd(flags))
	return cmd
}
