// Copyright 2026 Coach Workout Tools Contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWebwidgetsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "webwidgets",
		Short: "Manage webwidgets",
		Hidden: true,
	}

	cmd.AddCommand(newWebwidgetsWidgetActivitiesCmd(flags))
	cmd.AddCommand(newWebwidgetsWidgetLeaderboardCmd(flags))
	cmd.AddCommand(newWebwidgetsWidgetWodsCmd(flags))
	return cmd
}
