// Copyright 2026 Coach Workout Tools Contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newWebwidgetsWidgetWodsCmd(flags *rootFlags) *cobra.Command {
	var flagTrackIds string
	var flagDays int
	var flagDate string
	var flagSections string
	var flagLeaderboardLength int
	var flagActivityLength int

	cmd := &cobra.Command{
		Use:   "widget-wods",
		Short: "The gym-facing JSON API. Returns a wodset per track per day, each with the workout description and optionally the...",
		Example: "  btwb-pp-cli webwidgets widget-wods --track-ids example-value",
		Annotations: map[string]string{"pp:endpoint": "webwidgets.widget-wods", "pp:method": "GET", "pp:path": "https://webwidgets.prod.btwb.com/webwidgets/wods", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("track-ids") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "track-ids")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://webwidgets.prod.btwb.com/webwidgets/wods"
			params := map[string]string{}
			if flagTrackIds != "" {
				params["track_ids"] = fmt.Sprintf("%v", flagTrackIds)
			}
			if flagDays != 0 {
				params["days"] = fmt.Sprintf("%v", flagDays)
			}
			if flagDate != "" {
				params["date"] = fmt.Sprintf("%v", flagDate)
			}
			if flagSections != "" {
				params["sections"] = fmt.Sprintf("%v", flagSections)
			}
			if flagLeaderboardLength != 0 {
				params["leaderboard_length"] = fmt.Sprintf("%v", flagLeaderboardLength)
			}
			if flagActivityLength != 0 {
				params["activity_length"] = fmt.Sprintf("%v", flagActivityLength)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "webwidgets", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagTrackIds, "track-ids", "", "Track ids, comma separated. See `btwb-pp-cli track list`.")
	cmd.Flags().IntVar(&flagDays, "days", 0, "How many days back from `date` to return.")
	cmd.Flags().StringVar(&flagDate, "date", "", "Last day to return, as YYYY-MM-DD. The upstream expects a JavaScript `Date.toString()` value; this client converts.")
	cmd.Flags().StringVar(&flagSections, "sections", "", "Restrict to named WOD sections, comma separated.")
	cmd.Flags().IntVar(&flagLeaderboardLength, "leaderboard-length", 0, "Leaderboard entries per workout, per sex. 0 omits them.")
	cmd.Flags().IntVar(&flagActivityLength, "activity-length", 0, "Recent results per workout. 0 omits them.")

	return cmd
}
