// Copyright 2026 Coach Workout Tools Contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"


type LoggedResult struct {
	Date string `json:"date"`
	DetailPath string `json:"detail_path"`
	IsPrescribed bool `json:"is_prescribed"`
	Notes string `json:"notes"`
	Result string `json:"result"`
	SessionId int `json:"session_id"`
	WorkoutName string `json:"workout_name"`
}

type Track struct {
	Following bool `json:"following"`
	Id int `json:"id"`
	Name string `json:"name"`
}

type TracksListResponse struct {
	Tracks json.RawMessage `json:"tracks"`
}

type WebwidgetsWidgetActivitiesResponse struct {
	Activities json.RawMessage `json:"activities"`
}

type WebwidgetsWidgetLeaderboardResponse struct {
	FemaleLeaderboard json.RawMessage `json:"female_leaderboard"`
	MaleLeaderboard json.RawMessage `json:"male_leaderboard"`
	WorkoutDescription string `json:"workout_description"`
	WorkoutName string `json:"workout_name"`
	WorkoutUrl string `json:"workout_url"`
}

type WebwidgetsWidgetWodsResponse struct {
	Wodsets json.RawMessage `json:"wodsets"`
}

type WhiteboardDay struct {
	Date string `json:"date"`
	MemberId int `json:"member_id"`
	Workouts json.RawMessage `json:"workouts"`
}

type WhiteboardGetMonthResponse struct {
	Days json.RawMessage `json:"days"`
	MemberId int `json:"member_id"`
}

type WidgetResult struct {
	IsPersonalRecord bool `json:"is_personal_record"`
	IsPrescribed bool `json:"is_prescribed"`
	MemberLogoUrl string `json:"member_logo_url"`
	MemberName string `json:"member_name"`
	Notes string `json:"notes"`
	Result string `json:"result"`
	ResultUrl string `json:"result_url"`
	SessionTime string `json:"session_time"`
	TimeAgo string `json:"time_ago"`
	WorkoutName string `json:"workout_name"`
}

type Wod struct {
	Category string `json:"category"`
	Description string `json:"description"`
	EventId int `json:"event_id"`
	Instructions string `json:"instructions"`
	Kind string `json:"kind"`
	LogPath string `json:"log_path"`
	Movements json.RawMessage `json:"movements"`
	Name string `json:"name"`
	PreviousResult string `json:"previous_result"`
	ResultsCount int `json:"results_count"`
	ResultsPath string `json:"results_path"`
	TrackName string `json:"track_name"`
	Variant string `json:"variant"`
}

type WodEntry struct {
	DetailPath string `json:"detail_path"`
	EventId int `json:"event_id"`
	Kind string `json:"kind"`
	Title string `json:"title"`
	TrackId int `json:"track_id"`
	TrackName string `json:"track_name"`
}

type WodSet struct {
	Date string `json:"date"`
	DateString string `json:"date_string"`
	Entries json.RawMessage `json:"entries"`
	TrackName string `json:"track_name"`
}

type WorkoutSessionsListSessionsResponse struct {
	Sessions json.RawMessage `json:"sessions"`
}
